version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    volumes:
        - ./auth-service/src:/usr/src/app/src  
        - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - redis

#  payments-service:
#    build: ./payments-service
#    ports:
#      - "3002:3000"
#    depends_on:
#      - db

#  resource-service:
#    build: ./resource-service
#    ports:
#      - "3003:3000"
#    depends_on:
#      - db

 
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

volumes:
  postgres_data:
